export {default as HomePage} from "./HomePage";
export {default as AboutPage} from "./AboutPage";
export {default as PortfolioPage} from "./PortfolioPage";
export {default as ServicePage} from "./ServicePage";
export {default as PricePage} from "./PricePage";
export {default as TestimonialPage} from "./TestimonialPage";
export {default as ArticlePage} from "./ArticlePage";
export {default as ContactPage} from "./ContactPage";
export {default as AuthPage} from "./AuthPage";